### PR TITLE
(maint) pdk and repo standards update

### PR DESCRIPTION
**Pull request by heathseals**

### CODE REVIEW

**Comment by yachub** [comment]
Since the GH action only runs on PRs and it's not in the default branch yet, you may need to run `pdk test unit` and `pdk validate` locally first and see and fix any issues detected with all the new lint gems.

**Comment by heathseals** [comment]
@yachub yup, this was meant to be a draft as it will be a bit before I can circle back and address the issues.

**Comment by heathseals** [comment]
`pdk test unit` and `pdk validate` are :white_check_mark:

**Comment by heathseals** [comment]
ping @yachub .  i think the changes from https://github.com/ploperations/repo_standards/pull/9/ have been pulled into the PR.

**Review by genebean — APPROVED** [review]
LGTM

**Pull request merged**
